/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tao_controllerd_SerialPort */

#ifndef _Included_com_tao_controllerd_SerialPort
#define _Included_com_tao_controllerd_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tao_controllerd_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_tao_controllerd_SerialPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_tao_controllerd_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tao_controllerd_SerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     com_tao_controllerd_SerialPort
 * Method:    waitForRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tao_controllerd_SerialPort_waitForRead
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
